[package]
name = "patina"
version = "0.0.1"
authors = ["James Hannah <jhannah8124@gmail.com>"]
repository = "https://github.com/cyborgsphinx/patina"
license = "MIT"

[[bin]]
name = "patina"

[dependencies]
glob = "0.2"
copperline = "0.3"
nix = "0.5"
